default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: thisdevrocks_api_development
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD", '') %>
  host: localhost

test:
  <<: *default
  database: thisdevrocks_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
